### ISSUE TITLE
v1.1 TODO List

### ISSUE THREAD

**Issue by TheDiamondYT1** [EvolSoft/PocketUHC#1]
### Hello! This is the TODO list for v1.1 of PocketUHC.
- [ ] Golden Heads
- [ ] Stop food from regening health
- [ ] Options to block nether
- [ ] Options to block strength 2, speed 2 etc
- [ ] /uhc <stats> (Will add more commands next version)
- [ ] Option to death ban!
- [ ] Disallow people joining when a match is on
